ci:
    autoupdate_schedule: monthly
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: name-tests-test
    -   id: debug-statements
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
    -   id: double-quote-string-fixer
    -   id: check-merge-conflict
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies:
            -   flake8-typing-imports
            -   flake8-comprehensions
            -   flake8-noqa
            -   flake8-ban-utcnow
        args: ["--min-python-version=3.9"]
-   repo: https://github.com/hhatto/autopep8
    rev: v2.0.4
    hooks:
    -   id: autopep8
-   repo: https://github.com/jkittner/double-indent
    rev: 0.1.4
    hooks:
    -    id: double-indent
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
        args: [--py39-plus]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies: ['types-freezegun']
